/*
 * Alle Texte des Wertrechners in Deutsch und Englisch. Im Code steht kein
 * Fließtext; die Oberfläche greift über t('schluessel') zu.
 *
 * Fachbegriffe (Englisch): Bodenrichtwert = standard land value,
 * Sachwertverfahren = cost approach, Ertragswertverfahren = income approach,
 * Liegenschaftszinssatz = property yield (capitalisation rate),
 * Baulast = public easement (Baulast), Wohnlage = residential location class.
 */

export const TEXTE = {
  de: {
    sprache: 'de-DE',
    titel: 'Wertrechner',
    untertitel: 'Unverbindliche Wertindikation für Häuser und Mietshäuser in Berlin nach der ImmoWertV 2021',
    einleitung: 'In wenigen Schritten erhalten Sie eine Wertspanne nach dem Modell des Gutachterausschusses für Grundstückswerte in Berlin. Der Bodenrichtwert wird automatisch aus der Adresse ermittelt. Alles rechnet in Ihrem Browser; es werden keine Daten übertragen.',
    start: 'Jetzt starten',
    weiter: 'Weiter',
    zurueck: 'Zurück',
    berechnen: 'Wertindikation berechnen',
    neu: 'Neue Berechnung',
    schritt: 'Schritt {n} von {gesamt}',
    pflicht: 'Pflichtangabe',
    optional: 'optional',
    wasIstDas: 'Was ist das?',
    laden: 'Daten werden geladen …',
    fehlerLaden: 'Die Daten konnten nicht geladen werden. Bitte laden Sie die Seite neu.',
    fehlerPflicht: 'Bitte füllen Sie dieses Feld aus.',
    fehlerZahl: 'Bitte geben Sie eine Zahl ein.',
    fehlerBereich: 'Bitte geben Sie einen Wert zwischen {min} und {max} ein.',
    ja: 'Ja',
    nein: 'Nein',
    weissNicht: 'Weiß nicht',
    euro: '€',
    m2: 'm²',
    jahre: 'Jahre',

    // Schritt 1 – Objektart
    objektartTitel: 'Um welche Immobilie geht es?',
    objektartText: 'Der Rechner nutzt je nach Objektart das Sachwert- oder das Ertragswertverfahren – so, wie es der Berliner Gutachterausschuss für seine Marktdaten vorsieht.',
    objektart_efh: 'Einfamilienhaus',
    objektart_efh_text: 'auch mit Einliegerwohnung – Sachwertverfahren',
    objektart_zfh: 'Zweifamilienhaus',
    objektart_zfh_text: 'zwei Wohnungen, selbst genutzt oder vermietet – Sachwertverfahren',
    objektart_mfh: 'Mietshaus / Wohn- und Geschäftshaus',
    objektart_mfh_text: 'ab vier Mieteinheiten, Gewerbeanteil bis 80 % – Ertragswertverfahren',
    objektart_etw: 'Eigentumswohnung',
    objektart_etw_text: 'derzeit keine Berechnung, Anfrage möglich',
    etwTitel: 'Für Eigentumswohnungen berechnen wir keinen Wert',
    etwText: 'Der Berliner Gutachterausschuss veröffentlicht für Wohnungseigentum nur Vergleichsfaktoren „zur Verwendung für steuerliche Zwecke“. Sie eignen sich nicht als Grundlage einer Wertindikation. Gern schätzen wir Ihre Wohnung nach einer Besichtigung ein.',

    // Schritt 2 – Adresse
    adresseTitel: 'Wo steht das Gebäude?',
    adresseText: 'Aus der Adresse ermitteln wir Bodenrichtwert, Richtwertzone, Wohnlage und Ortsteil – ohne Aufruf eines fremden Dienstes. Die Daten liegen auf dieser Website.',
    plz: 'Postleitzahl',
    plzHilfe: 'Berliner Postleitzahl, fünfstellig',
    plzFehlt: 'Diese Postleitzahl liegt nicht in Berlin oder ist uns nicht bekannt.',
    strasse: 'Straße',
    strasseHilfe: 'Tippen Sie die ersten Buchstaben und wählen Sie aus der Liste.',
    strasseFehlt: 'Bitte wählen Sie eine Straße aus der Liste.',
    hausnummer: 'Hausnummer',
    hausnummerFehlt: 'Bitte wählen Sie die Hausnummer.',
    hausnummerHilfe: 'Fehlt Ihre Hausnummer? Dann wählen Sie die nächstgelegene; die Richtwertzone ist in der Regel dieselbe.',
    adressfundTitel: 'Gefunden',
    brwModell: 'Bodenrichtwert zum Modellstichtag {datum}',
    brwAktuell: 'aktueller Bodenrichtwert ({datum})',
    brwErklaerung: 'Für die Berechnung gilt der Bodenrichtwert zum 01.01.2024. Grund: Die Berliner Sachwertfaktoren und Liegenschaftszinssätze 2025 wurden mit genau diesem Stichtag abgeleitet (Modellkonformität, § 10 ImmoWertV). Der aktuelle Bodenrichtwert dient nur zur Information.',
    zone: 'Richtwertzone',
    nutzungZone: 'Nutzung',
    gfzZone: 'gebietstypische GFZ',
    wohnlage: 'Wohnlage',
    wohnlage_1: 'einfach',
    wohnlage_2: 'mittel',
    wohnlage_3: 'gut',
    wohnlage_0: 'nicht hinterlegt',
    wohnlageErklaerung: 'Die Wohnlage stammt aus dem Straßenverzeichnis zum Berliner Mietspiegel 2024 und fließt in den Sachwertfaktor ein.',
    ortsteil: 'Ortsteil',
    altbezirk: 'Altbezirk',
    quelleBrw: 'Bodenrichtwerte: Gutachterausschuss für Grundstückswerte in Berlin, Geoportal Berlin, Stichtage 01.01.2024 (Modell) und 01.01.2026 (aktuell), Datenlizenz Deutschland – Zero – 2.0. Adressen: Geoportal Berlin. Wohnlagen: Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen, Mietspiegel 2024.',
    keinBauland: 'Diese Richtwertzone ist kein Wohnbauland („{nutzung}“). Dafür können wir keine Indikation berechnen.',

    // Schritt 3 – Grundstück
    grundstueckTitel: 'Das Grundstück',
    grundstueckText: 'Die Grundstücksfläche steht im Grundbuch, im Kaufvertrag oder im Flurstücksnachweis.',
    grundstuecksflaeche: 'Grundstücksfläche',
    flurstueck: 'Flurstück',
    flurstueckHilfe: 'Nur zur Information in Ihrer Anfrage, ohne Einfluss auf die Berechnung.',
    grossesGrundstueck: 'Große Grundstücke: Ab etwa {max} m² liegen Sie außerhalb des Bereichs, für den der Gutachterausschuss die Faktoren abgeleitet hat. Dann ist keine Indikation möglich; oft ist ein Teil des Grundstücks gesondert zu bewerten.',

    // Schritt 4 – Gebäude (Sachwert)
    gebaeudeTitel: 'Das Gebäude',
    gebaeudeText: 'Diese Angaben bestimmen die Normalherstellungskosten, die Restnutzungsdauer und den Sachwertfaktor.',
    gebaeudestellung: 'Bauweise',
    stellung_freistehend: 'freistehend',
    stellung_doppelhaushaelfte: 'Doppelhaushälfte',
    stellung_reihenendhaus: 'Reihenendhaus',
    stellung_reihenmittelhaus: 'Reihenmittelhaus',
    keller: 'Unterkellerung',
    keller_ja: 'unterkellert (auch Teilkeller)',
    keller_nein: 'nicht unterkellert',
    kellerErklaerung: 'Teil- und Tiefkeller zählen im Berliner Modell als „unterkellert“.',
    geschosse: 'Vollgeschosse (ohne Keller und Dach)',
    geschosse_1: 'eingeschossig',
    geschosse_2: 'zweigeschossig',
    geschosse_3: 'dreigeschossig',
    dachgeschoss: 'Dachgeschoss',
    dach_voll_ausgebaut: 'ausgebaut',
    dach_voll_ausgebaut_text: 'mindestens zur Hälfte als Wohnraum',
    dach_nicht_ausgebaut: 'nicht ausgebaut',
    dach_nicht_ausgebaut_text: 'Dachboden, Abstellraum',
    dach_flachdach: 'Flachdach',
    dach_flachdach_text: 'oder flach geneigt, kein nutzbarer Dachraum',
    baujahr: 'Baujahr',
    baujahrErklaerung: 'Das ursprüngliche Baujahr (Bezugsfertigkeit). Modernisierungen verändern es im Berliner Modell nicht; sie zeigen sich im baulichen Zustand.',
    bauzustand: 'Baulicher Zustand',
    zustand_gut: 'gut',
    zustand_gut_text: 'neuwertig oder umfassend modernisiert, kaum Reparaturbedarf',
    zustand_normal: 'normal',
    zustand_normal_text: 'altersgemäß, kleinere Reparaturen fällig',
    zustand_schlecht: 'schlecht',
    zustand_schlecht_text: 'deutlicher Reparaturstau an Dach, Fassade oder Technik',
    zustandErklaerung: 'Einstufung nach dem Glossar des Gutachterausschusses. Der Zustand bestimmt die Restnutzungsdauer und eine Korrektur des Sachwertfaktors.',
    konstruktion: 'Konstruktion',
    konstruktion_massiv: 'Massivbau',
    konstruktion_fertighaus_massiv: 'Fertighaus massiv',
    konstruktion_fertighaus_holz: 'Fertighaus Holz',
    flaecheTitel: 'Größe des Gebäudes',
    flaecheText: 'Am genauesten ist die Brutto-Grundfläche (BGF). Kennen Sie sie nicht, reicht die Grundfläche nach Außenmaßen – oder ersatzweise die Wohnfläche.',
    flaeche_bgf: 'Brutto-Grundfläche',
    flaeche_bgf_hilfe: 'Summe aller Geschossflächen nach Außenmaßen einschließlich Keller und nutzbarem Dachgeschoss (DIN 277).',
    flaeche_grundflaeche: 'Grundfläche nach Außenmaßen',
    flaeche_grundflaeche_hilfe: 'Länge × Breite des Hauses außen, z. B. 10 m × 8 m = 80 m². Daraus leiten wir die BGF über die Geschosse ab.',
    flaeche_wohnflaeche: 'Wohnfläche',
    flaeche_wohnflaeche_hilfe: 'Nur als Schätzung geeignet; das Ergebnis wird entsprechend gekennzeichnet.',
    nebenanlagen: 'Besondere Nebenanlagen',
    nebenanlagenHilfe: 'Zeitwert von Garage, Carport, Gartenhaus oder aufwendigen Außenanlagen in Euro. Einfriedung, Hausanschlüsse und normale Wege sind im Bodenwert enthalten.',
    zweifamilienhausHinweis: 'Zweifamilienhäuser werden im Berliner Modell ohne Zuschlag wie Einfamilienhäuser berechnet.',

    // Schritt 4/5 – Gebäude und Mieten (Ertragswert)
    mietobjektTitel: 'Gebäude und Mieten',
    mietobjektText: 'Grundlage sind die tatsächlichen Nettokaltmieten je Monat und die Flächen. Der Liegenschaftszinssatz hängt von der durchschnittlichen Miete, der Lage und dem Gewerbeanteil ab.',
    ausstattungTitel: 'Ausstattung (Baujahre bis 1948)',
    zentralheizung: 'vollständig mit Zentral- oder Etagenheizung ausgestattet',
    baeder: 'alle Wohnungen mit Bad',
    wohnen: 'Wohnen',
    wohnflaecheGesamt: 'Wohnfläche gesamt',
    wohneinheiten: 'Anzahl Wohnungen',
    mieteWohnen: 'Nettokaltmiete Wohnen je Monat',
    gewerbe: 'Gewerbe',
    gewerbeVorhanden: 'Gewerbeflächen vorhanden',
    gewerbeflaeche: 'Gewerbefläche',
    mieteGewerbe: 'Nettokaltmiete Gewerbe je Monat',
    gewerbeart: 'Art der Gewerbefläche',
    gewerbe_buero_laden: 'Büro, Praxis, Laden',
    gewerbe_nebennutzung: 'Lager, Werkstatt (Nebennutzung)',
    sonstiges: 'Stellplätze und Garagen',
    garagen: 'Garagen',
    stellplaetze: 'offene Stellplätze',
    mieteSonstiges: 'Miete Stellplätze/Garagen je Monat',
    geschossflaeche: 'Geschossfläche aller oberirdischen Geschosse',
    geschossflaecheHilfe: 'Nach Außenmaßen, ohne Keller und nicht ausbaufähiges Dach. Daraus ergibt sich die wertrelevante GFZ, mit der der Bodenrichtwert angepasst wird. Unbekannt? Dann Grundfläche des Hauses × Zahl der Vollgeschosse.',

    // Schritt 6 – Besonderheiten
    besonderheitenTitel: 'Bekannte Besonderheiten',
    besonderheitenText: 'Diese Angaben verändern die Zahl nicht. Sie bestimmen unsere Hinweise und die Empfehlung am Ende.',
    besonderheit_bauschaeden: 'Bauschäden, Feuchte, Risse, Schimmel',
    besonderheit_altlasten: 'Altlasten oder Bodenbelastungen',
    besonderheit_baulasten: 'Baulasten',
    besonderheit_denkmal: 'Denkmalschutz',
    besonderheit_rechte: 'Rechte Dritter (Wegerecht, Wohnrecht, Nießbrauch, Erbbaurecht)',

    // Ergebnis
    ergebnisTitel: 'Unverbindliche Wertindikation',
    ergebnisSpanne: 'Wertspanne',
    ergebnisMitte: 'rechnerischer Wert',
    ergebnisVerfahren_sachwert: 'Sachwertverfahren nach §§ 35–39 ImmoWertV, Berliner Sachwertfaktoren 2025',
    ergebnisVerfahren_ertragswert: 'Allgemeines Ertragswertverfahren nach §§ 27–34 ImmoWertV, Berliner Liegenschaftszinssätze 2025',
    ergebnisStand: 'Marktdaten zum Stichtag {stichtag}; Bodenrichtwert {brwdatum}; Berechnung am {heute}.',
    ergebnisStreuung: 'Die Spanne von ±{prozent} % ist eine Orientierung. Einzelne Kaufpreise weichen laut Gutachterausschuss deutlich stärker ab (Verhältnis Kaufpreis zu Sachwert zwischen 0,64 und 1,63).',
    eckdaten: 'Eckdaten',
    rechenweg: 'Rechenweg Schritt für Schritt',
    rechenwegText: 'Jeder Schritt mit Formel, Ergebnis und Rechtsgrundlage. Faktoren werden wie in den Berliner Tabellen gerundet angewendet; der ungerundete Formelwert steht in Klammern.',
    spalteSchritt: 'Schritt',
    spalteFormel: 'Rechnung',
    spalteWert: 'Ergebnis',
    spalteGrundlage: 'Grundlage',
    faktorBestandteile: 'Zusammensetzung',
    modellparameter: 'Modellparameter',
    hinweise: 'Hinweise zu dieser Berechnung',
    nichtBeruecksichtigt: 'Was diese Indikation nicht berücksichtigt',
    nichtBeruecksichtigtListe: [
      'Bausubstanz und Bauschäden – keine Besichtigung, keine Prüfung von Dach, Fassade, Keller, Haustechnik',
      'Altlasten, Bodenbelastungen und Kampfmittel',
      'Baulasten, Denkmalschutz und öffentlich-rechtliche Beschränkungen',
      'Rechte und Belastungen in Abteilung II des Grundbuchs (Wegerechte, Wohnrechte, Nießbrauch, Erbbaurecht)',
      'Marktentwicklung nach dem Stichtag der Faktoren (31.12.2024)',
      'Besonderheiten wie Wasserlage, übergroße Grundstücke, Villen, Leerstand oder Paketverkäufe',
    ],
    rechtlich: 'Unverbindliche Wertindikation auf Grundlage allgemein veröffentlichter Marktdaten und Ihrer Angaben. Kein Gutachten, keine Verkehrswertermittlung nach § 194 BauGB, nicht für Beleihung, Gericht, Steuer oder Kaufentscheidung geeignet. Bausubstanz, Bauschäden, Altlasten, Baulasten, Rechte und Belastungen wurden nicht geprüft.',
    quellen: 'Quellen',
    ctaTitel: 'Sie möchten Gewissheit?',
    ctaText: 'Bei einer Vor-Ort-Prüfung bzw. technischen Due Diligence begutachten wir Bausubstanz, Schäden, Unterlagen und Risiken – als Grundlage für Kauf, Verkauf oder Finanzierung.',
    ctaTextBesonderheiten: 'Sie haben Besonderheiten angegeben oder sind sich unsicher. Genau dafür ist eine Vor-Ort-Prüfung gedacht: Wir begutachten Bausubstanz, Schäden, Unterlagen und Risiken.',
    ctaKnopf: 'Vor-Ort-Prüfung anfragen',
    ctaHinweis: 'Beim Klick öffnet sich Ihr E-Mail-Programm mit den Eckdaten dieser Berechnung. Erst wenn Sie die E-Mail senden, erreichen uns Ihre Angaben.',
    mailBetreff: 'Anfrage Vor-Ort-Prüfung – {adresse}',
    mailAnrede: 'Guten Tag,\n\nich bitte um ein Angebot für eine Vor-Ort-Prüfung. Eckdaten aus dem Wertrechner:\n',
    mailSchluss: '\nBitte melden Sie sich bei mir.\n\nMit freundlichen Grüßen\n',
    drucken: 'Ergebnis drucken',

    // Kein Ergebnis
    keinWertTitel: 'Hier können wir keine Zahl ausgeben',
    keinWertText: 'Das Berliner Modell ist für diesen Fall nicht abgesichert oder nicht anwendbar. Eine Indikation wäre nicht seriös. Gern bewerten wir das Objekt individuell.',
    grund_nicht_anwendbar: 'Warum nicht?',
    grund_ausserhalb: 'Außerhalb des Gültigkeitsbereichs',
    grund_liquidation: 'Das Gebäude trägt wirtschaftlich nicht mehr zum Wert bei',
    anfrageKnopf: 'Bewertung anfragen',

    // Fuß
    datenschutz: 'Datenschutz: Alle Eingaben bleiben in Ihrem Browser. Diese Seite setzt keine Cookies, nutzt kein Tracking und lädt ausschließlich Dateien von ing-bassam.de.',
    impressum: 'Impressum',
    datenschutzLink: 'Datenschutzerklärung',
    zurStartseite: 'Zur Startseite',
    sprachwechsel: 'English version',
    sprachwechselUrl: '/en/property-valuation/',

    // Fortschritt
    label_objektart: 'Objekt',
    label_adresse: 'Adresse',
    label_grundstueck: 'Grundstück',
    label_gebaeude: 'Gebäude',
    label_mietobjekt: 'Gebäude & Mieten',
    label_besonderheiten: 'Besonderheiten',
    label_ergebnis: 'Ergebnis',

    // Eckdaten und Modellparameter auf der Ergebnisseite
    ek_objekt: 'Objekt',
    ek_adresse: 'Adresse',
    ek_grundstueck: 'Grundstück',
    ek_gebaeude: 'Gebäude',
    ek_flaeche: 'Fläche',
    ek_baujahr: 'Baujahr / Zustand',
    ek_bodenwert: 'Bodenwert',
    ek_rohertrag: 'Jahresrohertrag',
    ek_reinertrag: 'Jahresreinertrag',
    ek_gebaeudesachwert: 'Sachwert Gebäude',
    ek_mieteinheiten: 'Mieteinheiten',
    mp_nhkTyp: 'NHK-2010-Gebäudetyp',
    mp_nhk: 'Normalherstellungskosten, Standardstufe {stufe}',
    mp_bgf: 'Brutto-Grundfläche',
    mp_bgf_grundflaeche: 'aus der Grundfläche abgeleitet',
    mp_bgf_wohnflaeche: 'aus der Wohnfläche geschätzt',
    mp_bpi: 'Baupreisindex (2010 = 100)',
    mp_regionalfaktor: 'Regionalfaktor',
    mp_gnd: 'Gesamtnutzungsdauer',
    mp_alter: 'Alter',
    mp_rnd: 'Restnutzungsdauer (Berliner Tabelle)',
    mp_brw: 'Bodenrichtwert zum {datum}',
    mp_brwAktuell: 'Bodenrichtwert aktuell',
    mp_wohnlage: 'Stadträumliche Wohnlage',
    mp_altbezirk: 'Altbezirk / Gruppe der Sachwertfaktoren',
    mp_swf: 'Sachwertfaktor (gerundet / Formel)',
    mp_lz: 'Liegenschaftszinssatz (gerundet / Formel)',
    mp_objektmiete: 'Ø Objektkaltmiete je m² Wohn-/Nutzfläche',
    mp_gewerbeanteil: 'Gewerblicher Anteil am Rohertrag',
    mp_gebietsgruppe: 'Gebietsgruppe / Stadtlage',
    mp_gfz: 'GFZ Richtwertzone / Grundstück',
    mp_gfzFaktor: 'GFZ-Anpassung des Bodenrichtwerts',
    mp_stichtag: 'Stichtag der Faktoren',
    einheit_euro_m2: '€/m²',
    einheit_prozent: '%',
    besonderheitenAngegeben: 'Angegebene Besonderheiten: {liste}',
    keineBesonderheiten: 'Keine Besonderheiten angegeben.',
  },

  en: {
    sprache: 'en-GB',
    titel: 'Property Value Calculator',
    untertitel: 'Non-binding value indication for houses and apartment buildings in Berlin under the German valuation ordinance (ImmoWertV 2021)',
    einleitung: 'In a few steps you receive a value range based on the model of the Berlin Committee of Valuation Experts (Gutachterausschuss). The standard land value is looked up automatically from the address. Everything is calculated in your browser; no data is transmitted.',
    start: 'Start',
    weiter: 'Continue',
    zurueck: 'Back',
    berechnen: 'Calculate value indication',
    neu: 'New calculation',
    schritt: 'Step {n} of {gesamt}',
    pflicht: 'required',
    optional: 'optional',
    wasIstDas: 'What is this?',
    laden: 'Loading data …',
    fehlerLaden: 'The data could not be loaded. Please reload the page.',
    fehlerPflicht: 'Please fill in this field.',
    fehlerZahl: 'Please enter a number.',
    fehlerBereich: 'Please enter a value between {min} and {max}.',
    ja: 'Yes',
    nein: 'No',
    weissNicht: 'Not sure',
    euro: '€',
    m2: 'm²',
    jahre: 'years',

    objektartTitel: 'Which type of property?',
    objektartText: 'Depending on the type, the calculator uses the cost approach or the income approach – exactly as the Berlin Committee of Valuation Experts prescribes for its market data.',
    objektart_efh: 'Detached or terraced house',
    objektart_efh_text: 'single-family house, also with granny flat – cost approach',
    objektart_zfh: 'Two-family house',
    objektart_zfh_text: 'two dwellings, owner-occupied or let – cost approach',
    objektart_mfh: 'Apartment building / mixed-use building',
    objektart_mfh_text: 'at least four rental units, commercial share up to 80 % – income approach',
    objektart_etw: 'Condominium (Eigentumswohnung)',
    objektart_etw_text: 'no calculation at present, enquiry possible',
    etwTitel: 'We do not calculate values for condominiums',
    etwText: 'For condominiums the Berlin Committee of Valuation Experts only publishes comparison factors “for tax purposes”. They are not a sound basis for a value indication. We are happy to assess your flat after an inspection.',

    adresseTitel: 'Where is the building?',
    adresseText: 'From the address we derive the standard land value (Bodenrichtwert), its zone, the residential location class and the district – without calling any third-party service. The data is hosted on this website.',
    plz: 'Postcode',
    plzHilfe: 'Berlin postcode, five digits',
    plzFehlt: 'This postcode is not in Berlin or unknown to us.',
    strasse: 'Street',
    strasseHilfe: 'Type the first letters and choose from the list.',
    strasseFehlt: 'Please choose a street from the list.',
    hausnummer: 'House number',
    hausnummerFehlt: 'Please choose the house number.',
    hausnummerHilfe: 'Number missing? Choose the nearest one; the land value zone is usually the same.',
    adressfundTitel: 'Found',
    brwModell: 'Standard land value at the model date {datum}',
    brwAktuell: 'current standard land value ({datum})',
    brwErklaerung: 'The calculation uses the standard land value as of 1 January 2024. Reason: the Berlin cost-approach factors and property yields 2025 were derived with exactly this date (model conformity, § 10 ImmoWertV). The current value is shown for information only.',
    zone: 'Land value zone',
    nutzungZone: 'Use',
    gfzZone: 'typical floor space index (GFZ)',
    wohnlage: 'Residential location class',
    wohnlage_1: 'basic',
    wohnlage_2: 'medium',
    wohnlage_3: 'good',
    wohnlage_0: 'not recorded',
    wohnlageErklaerung: 'The location class comes from the street index of the Berlin rent index (Mietspiegel 2024) and feeds into the cost-approach factor.',
    ortsteil: 'Locality',
    altbezirk: 'Former district',
    quelleBrw: 'Standard land values: Gutachterausschuss für Grundstückswerte in Berlin, Geoportal Berlin, reference dates 1 Jan 2024 (model) and 1 Jan 2026 (current), Datenlizenz Deutschland – Zero – 2.0. Addresses: Geoportal Berlin. Location classes: Senate Department for Urban Development, Building and Housing, Mietspiegel 2024.',
    keinBauland: 'This land value zone is not residential building land (“{nutzung}”). We cannot calculate an indication for it.',

    grundstueckTitel: 'The plot',
    grundstueckText: 'The plot area is stated in the land register, the purchase contract or the cadastral extract.',
    grundstuecksflaeche: 'Plot area',
    flurstueck: 'Cadastral parcel (Flurstück)',
    flurstueckHilfe: 'For information in your enquiry only; no effect on the calculation.',
    grossesGrundstueck: 'Large plots: from about {max} m² you are outside the range for which the committee derived its factors. No indication is possible then; often part of the plot has to be valued separately.',

    gebaeudeTitel: 'The building',
    gebaeudeText: 'These details determine the normal construction costs, the remaining useful life and the cost-approach factor.',
    gebaeudestellung: 'Building type',
    stellung_freistehend: 'detached',
    stellung_doppelhaushaelfte: 'semi-detached',
    stellung_reihenendhaus: 'end-terrace',
    stellung_reihenmittelhaus: 'mid-terrace',
    keller: 'Basement',
    keller_ja: 'with basement (also partial)',
    keller_nein: 'no basement',
    kellerErklaerung: 'Partial and low basements count as “with basement” in the Berlin model.',
    geschosse: 'Full storeys (excluding basement and attic)',
    geschosse_1: 'one storey',
    geschosse_2: 'two storeys',
    geschosse_3: 'three storeys',
    dachgeschoss: 'Attic',
    dach_voll_ausgebaut: 'converted',
    dach_voll_ausgebaut_text: 'at least half used as living space',
    dach_nicht_ausgebaut: 'not converted',
    dach_nicht_ausgebaut_text: 'loft, storage',
    dach_flachdach: 'flat roof',
    dach_flachdach_text: 'or low-pitched, no usable roof space',
    baujahr: 'Year of construction',
    baujahrErklaerung: 'The original year of completion. Refurbishments do not change it in the Berlin model; they show in the building condition.',
    bauzustand: 'Building condition',
    zustand_gut: 'good',
    zustand_gut_text: 'as new or comprehensively refurbished, hardly any repairs needed',
    zustand_normal: 'normal',
    zustand_normal_text: 'in keeping with its age, minor repairs due',
    zustand_schlecht: 'poor',
    zustand_schlecht_text: 'significant backlog on roof, façade or services',
    zustandErklaerung: 'Classification according to the committee’s glossary. The condition determines the remaining useful life and an adjustment of the cost-approach factor.',
    konstruktion: 'Construction',
    konstruktion_massiv: 'masonry',
    konstruktion_fertighaus_massiv: 'prefabricated, masonry',
    konstruktion_fertighaus_holz: 'prefabricated, timber',
    flaecheTitel: 'Size of the building',
    flaecheText: 'Most accurate is the gross floor area (BGF). If you do not know it, the footprint by external dimensions is enough – or, as a fallback, the living area.',
    flaeche_bgf: 'Gross floor area (BGF)',
    flaeche_bgf_hilfe: 'Sum of all floor areas by external dimensions including basement and usable attic (DIN 277).',
    flaeche_grundflaeche: 'Footprint by external dimensions',
    flaeche_grundflaeche_hilfe: 'Length × width of the house outside, e.g. 10 m × 8 m = 80 m². We derive the gross floor area from the storeys.',
    flaeche_wohnflaeche: 'Living area',
    flaeche_wohnflaeche_hilfe: 'Suitable as an estimate only; the result is marked accordingly.',
    nebenanlagen: 'Special outbuildings',
    nebenanlagenHilfe: 'Current value of garage, carport, garden house or elaborate outdoor facilities in euros. Fencing, service connections and normal paths are included in the land value.',
    zweifamilienhausHinweis: 'Two-family houses are calculated like single-family houses in the Berlin model, without a surcharge.',

    mietobjektTitel: 'Building and rents',
    mietobjektText: 'The basis is the actual net cold rent per month and the floor areas. The property yield (capitalisation rate) depends on the average rent, the location and the commercial share.',
    ausstattungTitel: 'Fit-out (built up to 1948)',
    zentralheizung: 'fully equipped with central or floor heating',
    baeder: 'all flats with bathroom',
    wohnen: 'Residential',
    wohnflaecheGesamt: 'Total living area',
    wohneinheiten: 'Number of flats',
    mieteWohnen: 'Net cold rent, residential, per month',
    gewerbe: 'Commercial',
    gewerbeVorhanden: 'Commercial units present',
    gewerbeflaeche: 'Commercial floor area',
    mieteGewerbe: 'Net cold rent, commercial, per month',
    gewerbeart: 'Type of commercial space',
    gewerbe_buero_laden: 'office, practice, shop',
    gewerbe_nebennutzung: 'storage, workshop (ancillary)',
    sonstiges: 'Parking spaces and garages',
    garagen: 'Garages',
    stellplaetze: 'open parking spaces',
    mieteSonstiges: 'Rent for parking/garages per month',
    geschossflaeche: 'Floor area of all above-ground storeys',
    geschossflaecheHilfe: 'By external dimensions, without basement and non-convertible roof. This gives the value-relevant floor space index (GFZ) used to adjust the standard land value. Unknown? Footprint × number of full storeys.',

    besonderheitenTitel: 'Known particularities',
    besonderheitenText: 'These answers do not change the figure. They determine our notes and the recommendation at the end.',
    besonderheit_bauschaeden: 'Structural damage, damp, cracks, mould',
    besonderheit_altlasten: 'Contaminated land',
    besonderheit_baulasten: 'Public easements (Baulasten)',
    besonderheit_denkmal: 'Listed building status',
    besonderheit_rechte: 'Third-party rights (rights of way, rights of residence, usufruct, heritable building right)',

    ergebnisTitel: 'Non-binding value indication',
    ergebnisSpanne: 'Value range',
    ergebnisMitte: 'calculated value',
    ergebnisVerfahren_sachwert: 'Cost approach under §§ 35–39 ImmoWertV, Berlin cost-approach factors (Sachwertfaktoren) 2025',
    ergebnisVerfahren_ertragswert: 'General income approach under §§ 27–34 ImmoWertV, Berlin property yields (Liegenschaftszinssätze) 2025',
    ergebnisStand: 'Market data as of {stichtag}; standard land value {brwdatum}; calculated on {heute}.',
    ergebnisStreuung: 'The range of ±{prozent} % is an orientation. According to the committee, individual purchase prices deviate considerably more (ratio of price to cost value between 0.64 and 1.63).',
    eckdaten: 'Key figures',
    rechenweg: 'Calculation step by step',
    rechenwegText: 'Each step with formula, result and legal basis. Factors are applied rounded as in the Berlin tables; the unrounded formula value is shown in brackets.',
    spalteSchritt: 'Step',
    spalteFormel: 'Calculation',
    spalteWert: 'Result',
    spalteGrundlage: 'Basis',
    faktorBestandteile: 'Composition',
    modellparameter: 'Model parameters',
    hinweise: 'Notes on this calculation',
    nichtBeruecksichtigt: 'What this indication does not consider',
    nichtBeruecksichtigtListe: [
      'Building fabric and defects – no inspection, no check of roof, façade, basement or services',
      'Contaminated land and unexploded ordnance',
      'Public easements (Baulasten), listed status and other public-law restrictions',
      'Rights and encumbrances in section II of the land register (rights of way, rights of residence, usufruct, heritable building rights)',
      'Market development after the reference date of the factors (31 December 2024)',
      'Special features such as waterfront location, oversized plots, villas, vacancy or portfolio sales',
    ],
    rechtlich: 'Non-binding value indication based on publicly available market data and your input. Not an appraisal, not a market value determination under § 194 BauGB, not suitable for lending, court, tax or purchase decisions. Building fabric, defects, contamination, public easements, rights and encumbrances have not been examined.',
    quellen: 'Sources',
    ctaTitel: 'Want certainty?',
    ctaText: 'In an on-site inspection or technical due diligence we examine the building fabric, defects, documents and risks – as a basis for purchase, sale or financing.',
    ctaTextBesonderheiten: 'You have indicated particularities or are unsure. That is exactly what an on-site inspection is for: we examine the building fabric, defects, documents and risks.',
    ctaKnopf: 'Request on-site inspection',
    ctaHinweis: 'Clicking opens your e-mail program with the key figures of this calculation. Your data only reaches us when you send the e-mail.',
    mailBetreff: 'Request for on-site inspection – {adresse}',
    mailAnrede: 'Dear Sir or Madam,\n\nplease send me an offer for an on-site inspection. Key figures from the value calculator:\n',
    mailSchluss: '\nPlease get back to me.\n\nKind regards\n',
    drucken: 'Print result',

    keinWertTitel: 'We cannot give a figure here',
    keinWertText: 'The Berlin model is not validated or not applicable for this case. An indication would not be reliable. We are happy to assess the property individually.',
    grund_nicht_anwendbar: 'Why not?',
    grund_ausserhalb: 'Outside the validated range',
    grund_liquidation: 'The building no longer contributes economically to the value',
    anfrageKnopf: 'Request a valuation',

    datenschutz: 'Privacy: all input stays in your browser. This page sets no cookies, uses no tracking and loads files from ing-bassam.de only.',
    impressum: 'Legal notice',
    datenschutzLink: 'Privacy policy',
    zurStartseite: 'Home',
    sprachwechsel: 'Deutsche Version',
    sprachwechselUrl: '/wertrechner/',

    label_objektart: 'Property',
    label_adresse: 'Address',
    label_grundstueck: 'Plot',
    label_gebaeude: 'Building',
    label_mietobjekt: 'Building & rents',
    label_besonderheiten: 'Particularities',
    label_ergebnis: 'Result',

    ek_objekt: 'Property',
    ek_adresse: 'Address',
    ek_grundstueck: 'Plot',
    ek_gebaeude: 'Building',
    ek_flaeche: 'Area',
    ek_baujahr: 'Year built / condition',
    ek_bodenwert: 'Land value',
    ek_rohertrag: 'Annual gross income',
    ek_reinertrag: 'Annual net income',
    ek_gebaeudesachwert: 'Cost value of building',
    ek_mieteinheiten: 'Rental units',
    mp_nhkTyp: 'NHK 2010 building type',
    mp_nhk: 'Normal construction costs, standard level {stufe}',
    mp_bgf: 'Gross floor area (BGF)',
    mp_bgf_grundflaeche: 'derived from the footprint',
    mp_bgf_wohnflaeche: 'estimated from the living area',
    mp_bpi: 'Construction price index (2010 = 100)',
    mp_regionalfaktor: 'Regional factor',
    mp_gnd: 'Total useful life',
    mp_alter: 'Age',
    mp_rnd: 'Remaining useful life (Berlin table)',
    mp_brw: 'Standard land value as of {datum}',
    mp_brwAktuell: 'Standard land value, current',
    mp_wohnlage: 'Residential location class',
    mp_altbezirk: 'Former district / cost-factor group',
    mp_swf: 'Cost-approach factor (rounded / formula)',
    mp_lz: 'Property yield (rounded / formula)',
    mp_objektmiete: 'Average net rent per m² of lettable area',
    mp_gewerbeanteil: 'Commercial share of gross income',
    mp_gebietsgruppe: 'Area group / city part',
    mp_gfz: 'Floor space index zone / plot',
    mp_gfzFaktor: 'FSI adjustment of the land value',
    mp_stichtag: 'Reference date of the factors',
    einheit_euro_m2: '€/m²',
    einheit_prozent: '%',
    besonderheitenAngegeben: 'Particularities indicated: {liste}',
    keineBesonderheiten: 'No particularities indicated.',
  },
};

/** Liefert eine Übersetzungsfunktion für eine Sprache: t('schritt', { n: 2, gesamt: 6 }). */
export function uebersetzer(sprache) {
  const w = TEXTE[sprache] || TEXTE.de;
  return (schluessel, werte) => {
    let text = w[schluessel] ?? TEXTE.de[schluessel] ?? schluessel;
    if (werte && typeof text === 'string') {
      for (const [k, v] of Object.entries(werte)) text = text.replaceAll(`{${k}}`, String(v));
    }
    return text;
  };
}
